
factorial: factorial.c
	gcc factorial.c -o factorial.out
	./factorial.out

palindrome-numbers: palindrome-numbers.c
	gcc palindrome-numbers.c -o palindrome-numbers.out
	./palindrome-numbers.out

count-digits: count-digits.c
	gcc count-digits.c -o count-digits.out
	./count-digits.out

clean:
	rm -r *.out
