run_all: largest_array max_difference reverse_array search_sorted_array


largest_array: largest_array.c array_utils.c
	gcc array_utils.c largest_array.c -o largest_array.out
	./largest_array.out


max_difference: max_difference.c array_utils.c
	gcc array_utils.c max_difference.c -o max_difference.out
	./max_difference.out


reverse_array: reverse_array.c array_utils.c
	gcc array_utils.c reverse_array.c -o reverse_array.out
	./reverse_array.out


search_sorted_array: search_sorted_array.c array_utils.c
	gcc array_utils.c search_sorted_array.c -o search_sorted_array.out
	./search_sorted_array.out


max_subarray: max_subarray.c array_utils.c
	gcc array_utils.c max_subarray.c -o max_subarray.out
	./max_subarray.out


clean:
	rm -r *.out
